-- Use Database and schema
USE DATABASE LA_DB;
USE SCHEMA LA_SCHEMA;

-- Use warehouse
USE WAREHOUSE COMPUTE_WH;

-- CREATE A PERMANENT TABLE
CREATE OR REPLACE TABLE PERMANENT_TABLE(
ID NUMBER,
NAME VARCHAR,
DATE DATE
);

-- CREATE A TRANSIENT TABLE
CREATE OR REPLACE TRANSIENT TABLE TRANSIENT_TABLE(
ID NUMBER,
NAME VARCHAR,
DATE DATE
);

-- CREATE A TEMPORARY TABLE
--  THE SCOPE OF THIS TEMPORARY TABLE IS WITHIN THE SESSION
CREATE OR REPLACE TEMPORARY TABLE TEMPORARY_TABLE(
ID NUMBER,
NAME VARCHAR,
DATE DATE
);

-- ADD DATA TO THE TABLES
INSERT INTO PERMANENT_TABLE VALUES (1, 'John', '2022-01-01');
INSERT INTO TRANSIENT_TABLE VALUES (2, 'Jane', '2022-01-02');
INSERT INTO TEMPORARY_TABLE VALUES (3, 'Jill', '2022-01-04');

-- DISPLAY TABLES METADATA
SHOW TABLES;

-- VIEW DATA FROM EACH TABLE
SELECT * FROM PERMANENT_TABLE;
SELECT * FROM TRANSIENT_TABLE;
SELECT * FROM TEMPORARY_TABLE;

-- CREATE CLONE FROM TABLES
/*
- Permanent table can be cloned into temporary or transient tables
- Temporary can be cloned into transient and vice versa.
- But, temporary or transient table CANNOT BE CLONED INTO PERMANENT TABLE
*/
CREATE TEMPORARY TABLE TEMPORARY_TABLE2 CLONE PERMANENT_TABLE;

SELECT * FROM TEMPORARY_TABLE2;

CREATE TRANSIENT TABLE TRANSIENT_TABLE2 CLONE PERMANENT_TABLE;

SELECT * FROM TRANSIENT_TABLE2;

CREATE TEMPORARY TABLE TEMPORARY_TABLE3 CLONE TRANSIENT_TABLE;

SELECT * FROM TEMPORARY_TABLE3;

CREATE TRANSIENT TABLE TRANSIENT_TABLE3 CLONE TEMPORARY_TABLE;

SELECT * FROM TRANSIENT_TABLE3;

-- CREATE TABLE PERMANENT_TABLE2 CLONE TEMPORARY_TABLE; -- Temp table cannot be cloned to a permanent table

-- CREATE TABLE PERMANENT_TABLE3 CLONE TRANSIENT_TABLE; -- Transient object cannot be cloned to a permanent object


-- ALTER RETENTION TIME
/*
Time travel (retention time):
Permanent table: 0-1 days (standard edition) | 0-90 days (enterprise and above)
Transient table: 0-1 days
Temporary table: 0-1 days
*/

ALTER TABLE PERMANENT_TABLE SET DATA_RETENTION_TIME_IN_DAYS = 90;

--THIS WILL THROUGH AN ERROR AS THE MAXIMUM RETENTION PERIOD FOR TRANSIENT TABLE IS 0-1 DAYS
-- ALTER TABLE TRANSIENT_TABLE SET DATA_RETENTION_TIME_IN_DAYS = 2;

ALTER TABLE TRANSIENT_TABLE SET DATA_RETENTION_TIME_IN_DAYS = 0;

-- THE MAXIMUM RETENTION PERIOD FOR TEMPORARY TABLE IS 0-1 DAYS
ALTER TABLE TEMPORARY_TABLE SET DATA_RETENTION_TIME_IN_DAYS = 0;

-- DISPLAY TABLES METADATA
SHOW TABLES;