-- Use database and schema
USE DATABASE LA_DB;
USE SCHEMA LA_SCHEMA;

-- Create a permanent table
CREATE OR REPLACE TABLE PERMANENT_TABLE(
ID NUMBER,
NAME VARCHAR,
DATE DATE
);

CREATE OR REPLACE TRANSIENT TABLE TRANSIENT_TABLE(
ID NUMBER,
NAME VARCHAR,
DATE DATE
);

CREATE OR REPLACE TEMPORARY TABLE TEMPORARY_TABLE(
ID NUMBER,
NAME VARCHAR,
DATE DATE
);

-- ADD DATA TO THE TABLES
INSERT INTO PERMANENT_TABLE (ID, NAME, DATE)
VALUES
(1, 'John', '2022-01-01');

INSERT INTO TRANSIENT_TABLE (ID, NAME, DATE)
VALUES
(2, 'Jane', '2022-01-02');

INSERT INTO TEMPORARY_TABLE (ID, NAME, DATE)
VALUES
(4, 'Jill', '2022-01-04');

--Display Tables Metadata
SHOW TABLES;

-- View data in the tables
SELECT * FROM PERMANENT_TABLE;
SELECT * FROM TRANSIENT_TABLE;
SELECT * FROM TEMPORARY_TABLE;

--CREATE CLONE FROM TABLES
CREATE TEMPORARY TABLE TEMPORARY_TABLE2 CLONE PERMANENT_TABLE;

SELECT * FROM TEMPORARY_TABLE2;

CREATE TRANSIENT TABLE TRANSIENT_TABLE2 CLONE PERMANENT_TABLE;

SELECT * FROM TRANSIENT_TABLE2;

-- ALTER RETENTION TIME
ALTER TABLE  PERMANENT_TABLE SET DATA_RETENTION_TIME_IN_DAYS = 32; -- limit 0 to 90 for versions Enterprise or higher
ALTER TABLE TRANSIENT_TABLE2 SET DATA_RETENTION_TIME_IN_DAYS = 0;
ALTER TABLE TEMPORARY_TABLE2 SET DATA_RETENTION_TIME_IN_DAYS = 32; -- THIS WILL THROW AN ERROR.

--display table metadata
SHOW TABLES;